"""Tier-2 drafts on approve — PO + supplier email (F-DRAFT-001, F-DRAFT-002)."""

from __future__ import annotations

import json
import os
from collections.abc import Callable
from datetime import UTC, datetime
from typing import Any
from uuid import UUID

from trita_decisions.audit import append_audit
from trita_decisions.draft_schemas import DraftSchemaError, validate_po_draft, validate_supplier_email

Tier2LlmFn = Callable[[str, dict[str, Any], dict[str, Any]], dict[str, Any] | None]

REORDER_TYPE = "INVENTORY_REORDER"
PO_ACTION = "create_po_draft"


def tier2_drafts_enabled() -> bool:
    raw = os.environ.get("TIER2_DRAFTS_ENABLED", "true").strip().lower()
    return raw not in ("0", "false", "no", "off")


def should_create_tier2_drafts(decision: dict[str, Any]) -> bool:
    if not tier2_drafts_enabled():
        return False
    if decision.get("type") != REORDER_TYPE:
        return False
    card = decision.get("card") or {}
    rec = card.get("recommendation") or {}
    return rec.get("action_template") == PO_ACTION


def _reorder_params(card: dict[str, Any]) -> tuple[str, int]:
    rec = card.get("recommendation") or {}
    params = rec.get("parameters") or {}
    sku_code = str(params.get("sku_code") or card.get("sku_id") or "SKU")
    try:
        qty = int(params.get("qty") or 0)
    except (TypeError, ValueError):
        qty = 0
    return sku_code, max(qty, 0)


def build_template_po_draft(
    *,
    decision_id: UUID,
    card: dict[str, Any],
) -> dict[str, Any]:
    sku_code, qty = _reorder_params(card)
    impact = card.get("impact") or {}
    today = datetime.now(UTC).strftime("%Y%m%d")
    supplier = "Primary supplier"
    return {
        "po_reference": f"DRAFT-{today}-{str(decision_id)[:8]}",
        "supplier_name": supplier,
        "supplier_email": "procurement@supplier.example",
        "currency": "INR",
        "line_items": [
            {
                "sku_code": sku_code,
                "description": f"Reorder {sku_code} per Trita recommendation",
                "qty": qty,
                "uom": "units",
            }
        ],
        "notes": (
            f"Draft PO for {sku_code}. Use approved qty {qty} only. "
            f"Horizon {impact.get('horizon_days', 14)} days. "
            "Generated by Trita Tier-2 (human executes; no external API write)."
        ),
        "requested_delivery_date": None,
    }


def build_template_supplier_email(
    *,
    po_draft: dict[str, Any],
    card: dict[str, Any],
) -> dict[str, Any]:
    sku_code, qty = _reorder_params(card)
    supplier = str(po_draft.get("supplier_name") or "Supplier")
    to_email = str(po_draft.get("supplier_email") or "procurement@supplier.example")
    po_ref = str(po_draft.get("po_reference") or "DRAFT")
    body = (
        f"Dear {supplier} team,\n\n"
        f"Please confirm availability for SKU {sku_code}, quantity {qty} units "
        f"(PO reference {po_ref}).\n\n"
        "This is a draft for human review — please verify against your ERP before placing.\n\n"
        "Regards,\nProcurement (via Trita)"
    )
    return {
        "subject": f"PO draft — {sku_code} × {qty} units ({po_ref})",
        "body_text": body,
        "to": [to_email],
        "line_items_summary": f"{sku_code}: {qty} units",
    }


def store_artifact(
    cur,
    *,
    tenant_id: UUID,
    decision_id: UUID,
    artifact_type: str,
    payload: dict[str, Any],
    source: str,
) -> UUID:
    cur.execute(
        """
        INSERT INTO public.decision_artifacts (
            tenant_id, decision_id, artifact_type, payload, source
        ) VALUES (
            %s, %s, %s::public.decision_artifact_type, %s::jsonb, %s
        )
        ON CONFLICT (decision_id, artifact_type)
        DO UPDATE SET
            payload = EXCLUDED.payload,
            source = EXCLUDED.source,
            created_at = now()
        RETURNING id
        """,
        (tenant_id, decision_id, artifact_type, json.dumps(payload), source),
    )
    row = cur.fetchone()
    assert row is not None
    return UUID(str(row[0]))


def list_artifacts(
    cur,
    tenant_id: UUID,
    decision_id: UUID,
) -> list[dict[str, Any]]:
    cur.execute(
        """
        SELECT id, artifact_type::text, payload, source, created_at
        FROM public.decision_artifacts
        WHERE tenant_id = %s AND decision_id = %s
        ORDER BY created_at ASC
        """,
        (tenant_id, decision_id),
    )
    return [
        {
            "id": str(r[0]),
            "artifact_type": r[1],
            "payload": r[2],
            "source": r[3],
            "created_at": r[4].isoformat() if r[4] else None,
        }
        for r in cur.fetchall()
    ]


def maybe_create_tier2_drafts(
    cur,
    *,
    tenant_id: UUID,
    decision_id: UUID,
    user_id: UUID,
    decision: dict[str, Any],
    llm_fn: Tier2LlmFn | None = None,
) -> dict[str, Any] | None:
    if not should_create_tier2_drafts(decision):
        return None

    card = decision.get("card") or {}
    if not isinstance(card, dict):
        return None

    sku_code, qty = _reorder_params(card)
    po_template = build_template_po_draft(decision_id=decision_id, card=card)
    po_source = "template"
    po_payload = po_template

    if llm_fn is not None:
        llm_po = llm_fn("po_draft", card, po_template)
        if llm_po:
            try:
                validate_po_draft(llm_po, expected_sku_code=sku_code, expected_qty=qty)
                po_payload = llm_po
                po_source = str(llm_po.get("_source") or "litellm")
            except DraftSchemaError:
                po_payload = po_template
                po_source = "template_fallback_schema"

    validate_po_draft(po_payload, expected_sku_code=sku_code, expected_qty=qty)
    po_id = store_artifact(
        cur,
        tenant_id=tenant_id,
        decision_id=decision_id,
        artifact_type="po_draft",
        payload=po_payload,
        source=po_source,
    )

    email_template = build_template_supplier_email(po_draft=po_payload, card=card)
    email_source = "template"
    email_payload = email_template

    if llm_fn is not None:
        llm_email = llm_fn("supplier_email", card, {"po_draft": po_payload, "email": email_template})
        if llm_email:
            try:
                validate_supplier_email(llm_email)
                email_payload = llm_email
                email_source = str(llm_email.get("_source") or "litellm")
            except DraftSchemaError:
                email_payload = email_template
                email_source = "template_fallback_schema"

    validate_supplier_email(email_payload)
    email_id = store_artifact(
        cur,
        tenant_id=tenant_id,
        decision_id=decision_id,
        artifact_type="supplier_email",
        payload=email_payload,
        source=email_source,
    )

    append_audit(
        cur,
        tenant_id=tenant_id,
        decision_id=decision_id,
        user_id=user_id,
        action="draft_created",
        projection_hash=decision.get("projection_hash") or "",
        reason_text=json.dumps({"po_artifact_id": str(po_id), "email_artifact_id": str(email_id)}),
    )

    return {
        "po_draft": po_payload,
        "supplier_email": email_payload,
        "artifact_ids": {"po_draft": str(po_id), "supplier_email": str(email_id)},
        "sources": {"po_draft": po_source, "supplier_email": email_source},
    }

